module.exports = {
  INITIATE_AUTH_ERR: 'Something went wrong while initiating auth.',
  GET_BY_USERNAME_ERR: 'Error occured while getting user by cognito username',
  GET_BY_COGNITO_ID_ERR: 'Error occured while getting user by cognito Id',
  ALREADY_EXIST_USERNAME: 'Have I seen you here before? It looks like someone is already using that username. Please try another one.',
  ALREADY_EXIST_EMAIL: 'What\'s this? It looks like someone is already using this email address. Do you have another you can use?',
  PRE_SIGNUP_ERR: 'Hold up. Something went wrong trying to sign you up. Let\'s try again.',
  GET_BY_SUB_ERR: 'Error occured while getting user by subId',
};
